import Link from 'next/link'
import '../../globals.css'
import { Inter, Quicksand } from 'next/font/google'
import { SessionProvider } from '../../providers/SessionProvider'
const inter = Inter({ subsets: ['latin'] })
const quicksand = Quicksand({ subsets: ['latin'] })
export const metadata = {
  title: 'Eco',
  description: 'Generated by create next app',
}

export default function AuthLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <meta charSet="utf-8" />
      <body className={inter.className}>
      <SessionProvider>
        <main className='min-h-full min-w-full'>
        <nav className='h-16 bg-white drop-shadow-md flex justify-between items-center align-middle'>
          <Link href="/">
          <p className={`${quicksand.className} font-semibold text-4xl text-primary mx-3`}>
          ECO</p>
          </Link>
        </nav>
        {children}
        </main>
        </SessionProvider>
        </body>
    </html>
  )
}
