import Link from 'next/link'
import './globals.css'
import { Inter, Quicksand } from 'next/font/google'
import {BiSearchAlt} from 'react-icons/bi'
import SearchInput from './searchInput'
const inter = Inter({ subsets: ['latin'] })
const quicksand = Quicksand({ subsets: ['latin'] })
export const metadata = {
  title: 'Eco',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <meta charSet="utf-8" />
      <body className={inter.className}>
        <nav className='h-16 bg-white drop-shadow-md flex justify-between items-center align-middle'>
          <p className={`${quicksand.className} font-semibold text-4xl text-emerald-800 mx-3`}>
          ECO</p>
          <SearchInput/>
          <div className='flex space-x-2'>
          <ul>
            <li>Write</li>
          </ul>
            <Link href="/api/auth/signin"> <p>
              User
            </p>
            </Link>
          </div>
        </nav>
        {children}
        </body>
    </html>
  )
}
