import Link from 'next/link'
import '../globals.css'
import { Inter, Quicksand } from 'next/font/google'
import SearchInput from './searchInput'
import {TiDocumentAdd} from 'react-icons/ti'
import UserProfile from  '@/components/userProfile'
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ['latin'] })
const quicksand = Quicksand({ subsets: ['latin'] })
import {SessionProvider} from '../providers/SessionProvider'
export const metadata = {
  title: 'Eco',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <meta charSet="utf-8" />
      <body className={inter.className}>
      <SessionProvider>
        <nav className='h-16 bg-white drop-shadow-md flex justify-between items-center align-middle'>
          <Link href="/">
          <p className={`${quicksand.className} font-semibold text-4xl text-primary mx-3`}>
          ECO</p>
          </Link>
          <SearchInput/>
          <div className='flex space-x-2'>
          <ul>
          <Link href="/posts/create"> 
          <div className="w-32 h-10 bg-accent rounded-lg flex align-middle items-center justify-center flex-row">
          <p className="text-white text-base font-semibold">Add post</p>
          <TiDocumentAdd className='text-white w-5 h-5'/>
          </div>
          </Link>
          </ul>
            <UserProfile/>
          </div>
        </nav>
        {children}
        </SessionProvider>
        <img src="/wave.svg" alt="wave" className="logo" />
        <ToastContainer/>
        </body>
    </html>
  )
}
